# Generated by Django 2.2 on 2020-12-04 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=200)),
                ('emali', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='g_stu.Grade')),
            ],
        ),
    ]
